### ISSUE TITLE
Cannot Found Challenge After Created

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/challenge-engine-ui#597]
## Steps to Reproduce:
- Login as Ghostar
- in **Test tass Project Created** project, click button **Launch New**
- Choose **Data Science** Track
- Choose type **Data Science**
- Fill challenge Name **Data Science Test**
- click button **create challenge**
- In Edit Challenge page, fill all necessary input and then click button **launch as Active**

## Actual Result:
Cannot found Challenge **Data Science Test** in active tab
![cant found challenge]( https://www.dropbox.com/s/fcu4s98nl7n97bt/cant_found_data%20science.png?raw=1)

## Video
https://www.dropbox.com/s/c39vt7euwcanzde/2020-05-09-10-17-35.avi?raw=1
## Expected Result:
Can find a challenge with name **Data Science Test** in active tab

## Device/OS/Browser Information:
- Device: Lenovo (laptop)
- Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
- RAM : 8 GB
- System Type: 64 Bit OS, x64-based processor
- Pen or touch: no pen or touch
- OS: Windows 10 Home Single Language
- Browser: Google Chrome (81.0.4044.138 (Official Build) (64-bit))

**Comment by acshields** [comment]
@vikasrohit @mtwomey - can we test this to see if we can reproduce the issue? If it is still valid, this would be an item that we may need to fix before prod-release.

**Comment by vikasrohit** [comment]
Yes, I can reproduce this and it is something which I described in our call as well. Essentially it is filtering out the challenge you create with some unknown access logic. This logic is not related to the project.
I am not able to see challenge created by others in a project where I have the access. I am not able  to see the challenge created by me in appropriate status (Active, New, etc).

**Comment by vikasrohit** [comment]
Possible reason https://github.com/topcoder-platform/challenge-api/issues/147

**Comment by vikasrohit** [comment]
@ lakshmiathreya can we get it retested? I have deployed a work around for it on dev.

**Comment by drasticdpk** [comment]
@vikasrohit unfortunately I am unable to create challenge, here is the reference :
https://monosnap.com/file/keheFUOORyVSSJtyZJXA0mFigPZwhB

**Comment by vikasrohit** [comment]
@drasticdpk are you able to test it now?

**Comment by drasticdpk** [comment]
Sorry @vikasrohit , still unable to create challenge. correct me if i missed anything from my end.
![image](https://user-images.githubusercontent.com/25297859/83789538-97d81180-a6b6-11ea-9ebd-3b149b551a5a.png)

**Comment by drasticdpk** [comment]
Verified on Dev Env cc @vikasrohit @lakshmiathreya
https://monosnap.com/file/pkXh2DiClFb6L5hrKHcc1x80eiZ0VT
